"""
Page 4: Explainability (XAI)
Information Visualization of model interpretability via SHAP and LIME.
Local attribution decomposition, multi-sample variance distributions, and cross-method concordance.
Spacious layout, clean typography, and comprehensive tooltips.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from models.model_loader import (
    load_test_data,
    load_thresholds,
    load_shap_global,
    load_shap_local,
    load_lime_local,
    load_shap_lime_comparison,
    load_explained_transaction,
    load_shap_sample_values,
)
from utils.visualization import (
    apply_dark_theme,
    COLOR_LEGIT,
    COLOR_FRAUD,
    COLOR_BORDER,
    COLOR_BG_CARD,
    COLOR_BG_DARK,
    COLOR_TEXT,
    COLOR_TEXT_BRIGHT,
    COLOR_TEXT_MUTED,
)


def show():
    st.subheader("Explainable AI & Visual Interpretability")
    st.markdown(
        "Dissecting deep neural network decisions using cooperative game theory (SHAP KernelExplainer) "
        "and localized surrogate approximations (LIME). Investigating feature contributions and cross-method alignment."
    )

    try:
        test_data = load_test_data()
        thresholds = load_thresholds()
        shap_global = load_shap_global()
        shap_local = load_shap_local()
        lime_local = load_lime_local()
        shap_lime_comp = load_shap_lime_comparison()
        explained_tx = load_explained_transaction()
        shap_sample_vals = load_shap_sample_values()
    except Exception as e:
        st.error(f"Error loading explainability artifacts: {str(e)}")
        return

    focal_idx = explained_tx.get("test_row_index", 12507)

    st.markdown("<div style='margin-top: 1.5rem;'></div>", unsafe_allow_html=True)

    # ──────────────────────────────────────────────────────────────────────────
    # Section 1: Decision Profile for Focal Transaction
    # ──────────────────────────────────────────────────────────────────────────
    st.markdown(f"### 1. Decision Profile: Benchmark Transaction #{focal_idx}")

    if focal_idx in test_data.index:
        tx_row = test_data.loc[focal_idx]
        actual_class = "Fraud" if tx_row["Actual_Class"] == 1 else "Legitimate"
        tabnet_prob = float(tx_row["TabNet_Probability"])
        tabnet_thresh = float(thresholds.get("TabNet", 0.997419))
        is_fraud = tx_row["TabNet_Prediction"] == 1

        c1, c2, c3, c4 = st.columns(4)
        c1.metric(
            "Explainer Target",
            "TabNet",
            help="Deep tabular architecture with attentive sequential feature selection explained by SHAP and LIME.",
        )
        c2.metric(
            "Output Probability",
            f"{tabnet_prob:.8e}",
            help="Predicted probability of fraud generated by TabNet for row #12507.",
        )
        c3.metric(
            "Decision Threshold",
            f"{tabnet_thresh:.6f}",
            help="Validation-calibrated decision threshold for TabNet (0.997419).",
        )
        c4.metric(
            "Classification",
            "FRAUD" if is_fraud else "LEGITIMATE",
            delta="Actual: " + actual_class,
            delta_color="normal" if not is_fraud else "inverse",
            help=f"Final binary decision compared against ground-truth class ({actual_class}).",
        )

        st.caption(
            f"Ground Truth: {actual_class}. Output probability ({tabnet_prob:.2e}) "
            f"falls far below threshold ({tabnet_thresh:.4f}), yielding a legitimate classification."
        )

    st.markdown("<div style='margin-top: 2rem;'></div>", unsafe_allow_html=True)
    st.markdown("---")

    # ──────────────────────────────────────────────────────────────────────────
    # Section 2: Local SHAP Attribution
    # ──────────────────────────────────────────────────────────────────────────
    st.markdown(f"### 2. Local Attribution: SHAP Values (Row #{focal_idx})")
    st.markdown(
        "Shapley Additive Explanations decompose the prediction into additive feature contributions. "
        "Crimson bars denote features pushing the decision toward Fraud; blue bars denote features pushing toward Legitimate."
    )

    tab_local_bar, tab_waterfall = st.tabs(["Diverging Attribution Spectrum", "Attribution Flow Table"])

    with tab_local_bar:
        nonzero_shap = shap_local[shap_local["SHAP_Value"] != 0].copy().sort_values("SHAP_Value", ascending=True)

        fig_local = go.Figure(
            go.Bar(
                x=nonzero_shap["SHAP_Value"],
                y=nonzero_shap["Feature"],
                orientation="h",
                marker_color=[
                    COLOR_FRAUD if val > 0 else COLOR_LEGIT for val in nonzero_shap["SHAP_Value"]
                ],
                text=[f"{val:+.6f}" for val in nonzero_shap["SHAP_Value"]],
                textposition="auto",
                hovertemplate="Feature: %{y}<br>SHAP Attribution: %{x:+.8f}<extra></extra>",
            )
        )
        apply_dark_theme(
            fig_local,
            height=440,
            title="Feature Attributions: Crimson = Towards Fraud (+), Blue = Towards Legitimate (-)",
        )
        fig_local.update_xaxes(title="SHAP Attribution Value")
        st.plotly_chart(fig_local, use_container_width=True)

    with tab_waterfall:
        c_w1, c_w2 = st.columns(2)
        with c_w1:
            st.markdown("**Features Promoting Fraud Classification (+)**")
            pos_df = shap_local[shap_local["SHAP_Value"] > 0].sort_values("SHAP_Value", ascending=False)
            if not pos_df.empty:
                st.dataframe(pos_df[["Feature", "SHAP_Value"]].style.format({"SHAP_Value": "{:+.8f}"}), use_container_width=True)
            else:
                st.caption("No positive features observed.")

        with c_w2:
            st.markdown("**Features Promoting Legitimate Classification (-)**")
            neg_df = shap_local[shap_local["SHAP_Value"] < 0].sort_values("SHAP_Value", ascending=True)
            if not neg_df.empty:
                st.dataframe(neg_df[["Feature", "SHAP_Value"]].style.format({"SHAP_Value": "{:+.8f}"}), use_container_width=True)
            else:
                st.caption("No negative features observed.")

    st.markdown("<div style='margin-top: 2rem;'></div>", unsafe_allow_html=True)
    st.markdown("---")

    # ──────────────────────────────────────────────────────────────────────────
    # Section 3: Multi-Sample SHAP Variance
    # ──────────────────────────────────────────────────────────────────────────
    st.markdown("### 3. Multi-Sample Explanation Stability (N = 20 Test Cases)")
    st.markdown(
        "Visualizing attribution distribution across the sample of 20 precomputed test transactions. "
        "Each dot represents a transaction's SHAP attribution for that feature, illustrating feature impact variance."
    )

    melted_shap = shap_sample_vals.melt(var_name="Feature", value_name="SHAP_Value")
    order = shap_sample_vals.abs().mean().sort_values(ascending=False).index.tolist()[:15]
    filtered_melted = melted_shap[melted_shap["Feature"].isin(order)]

    fig_strip = px.strip(
        filtered_melted,
        x="SHAP_Value",
        y="Feature",
        orientation="h",
        category_orders={"Feature": order[::-1]},
        color_discrete_sequence=["#58a6ff"],
    )
    apply_dark_theme(fig_strip, height=450, title="Distribution of SHAP Attributions Across 20 Test Cases")
    fig_strip.update_xaxes(title="SHAP Attribution Value")
    fig_strip.update_traces(
        jitter=0.4,
        marker=dict(size=6, opacity=0.8),
        hovertemplate="Feature: %{y}<br>SHAP Value: %{x:+.6f}<extra></extra>",
    )
    st.plotly_chart(fig_strip, use_container_width=True)
    st.caption(
        "Strip plot across 20 held-out test transactions. Features like V4, V11, and V14 display wide dispersion, "
        "indicating strong context-dependent swings between transactions."
    )

    st.markdown("<div style='margin-top: 2rem;'></div>", unsafe_allow_html=True)
    st.markdown("---")

    # ──────────────────────────────────────────────────────────────────────────
    # Section 4: Global Feature Importance
    # ──────────────────────────────────────────────────────────────────────────
    st.markdown("### 4. Global Feature Importance (TabNet KernelExplainer)")
    st.caption(
        "Computed using KernelExplainer with 500 reference training samples across 20 held-out test transactions. "
        "Preliminary global ranking representing general feature sensitivity."
    )

    top_k = st.slider(
        "Display Top Features:",
        min_value=5,
        max_value=30,
        value=15,
        help="Adjust the number of top features shown in the global importance chart.",
    )
    plot_g = shap_global.head(top_k).sort_values("Mean_Absolute_SHAP", ascending=True)

    fig_g = go.Figure(
        go.Bar(
            x=plot_g["Mean_Absolute_SHAP"],
            y=plot_g["Feature"],
            orientation="h",
            marker=dict(
                color=plot_g["Mean_Absolute_SHAP"],
                colorscale=[[0, "#21262d"], [1, "#58a6ff"]],
            ),
            text=[f"{v:.6f}" for v in plot_g["Mean_Absolute_SHAP"]],
            textposition="auto",
            hovertemplate="Feature: %{y}<br>Mean |SHAP|: %{x:.6f}<extra></extra>",
        )
    )
    apply_dark_theme(fig_g, height=max(360, top_k * 25), title=f"Top {top_k} Features by Mean Absolute SHAP")
    fig_g.update_xaxes(title="Mean |SHAP Attribution|")
    st.plotly_chart(fig_g, use_container_width=True)

    st.markdown("<div style='margin-top: 2rem;'></div>", unsafe_allow_html=True)
    st.markdown("---")

    # ──────────────────────────────────────────────────────────────────────────
    # Section 5: Local LIME Surrogate Explanations
    # ──────────────────────────────────────────────────────────────────────────
    st.markdown(f"### 5. Local Surrogate Rules: LIME (Row #{focal_idx})")
    st.markdown(
        "LIME fits an interpretable ridge regression within a perturbed neighborhood of the focal transaction. "
        "Continuous variables were discretized. Rules reference the standardized feature space."
    )

    sorted_lime = lime_local.sort_values("LIME_Weight", ascending=True)

    fig_lime = go.Figure(
        go.Bar(
            x=sorted_lime["LIME_Weight"],
            y=sorted_lime["LIME_Rule"],
            orientation="h",
            marker_color=[
                COLOR_FRAUD if w > 0 else COLOR_LEGIT for w in sorted_lime["LIME_Weight"]
            ],
            text=[f"{w:+.6f}" for w in sorted_lime["LIME_Weight"]],
            textposition="auto",
            hovertemplate="Rule: %{y}<br>Weight: %{x:+.6f}<extra></extra>",
        )
    )
    apply_dark_theme(fig_lime, height=400, title="LIME Local Surrogate Feature Weights")
    fig_lime.update_xaxes(title="Surrogate Model Weight")
    st.plotly_chart(fig_lime, use_container_width=True)

    with st.expander("LIME Decision Rules Table"):
        st.dataframe(lime_local, use_container_width=True, hide_index=True)

    st.markdown("<div style='margin-top: 2rem;'></div>", unsafe_allow_html=True)
    st.markdown("---")

    # ──────────────────────────────────────────────────────────────────────────
    # Section 6: SHAP vs LIME Concordance
    # ──────────────────────────────────────────────────────────────────────────
    st.markdown("### 6. Cross-Method Concordance: SHAP vs LIME")
    st.markdown(
        "Evaluating explanation consistency across distinct theoretical paradigms: "
        "Axiomatic Shapley values vs Local surrogate approximations."
    )

    c_c1, c_c2 = st.columns([1, 1])

    with c_c1:
        st.markdown("**Overlapping Feature Attributions**")
        st.dataframe(shap_lime_comp, use_container_width=True, hide_index=True)

    with c_c2:
        if "Direction_Agreement" in shap_lime_comp.columns:
            agreement_rate = (shap_lime_comp["Direction_Agreement"].sum() / len(shap_lime_comp)) * 100
            st.metric(
                "Directional Concordance",
                f"{agreement_rate:.0f}%",
                delta="100% on Shared Features",
                help="Proportion of overlapping features where both SHAP and LIME assign the same directional impact (Fraud vs Legitimate).",
            )

        st.caption(
            "Shared subset: Amount, V13, V12. For all three common features, "
            "both explainers agreed on the direction of influence."
        )

    st.markdown("<div style='margin-top: 2rem;'></div>", unsafe_allow_html=True)

    # Epistemological Caveats
    st.markdown("### Epistemological & Operational Caveats")
    st.markdown(
        """
        - **Local Scope:** Directional agreement observed here applies strictly to Row #12507. It does not establish global concordance across all transactions.
        - **Incommensurable Magnitudes:** SHAP values (probability shifts) and LIME weights (ridge coefficients) operate in distinct mathematical units and cannot be directly compared numerically.
        - **Consistency vs Truth:** Cross-method alignment proves algorithmic consistency, not that the explanation represents absolute ground truth.
        - **Absence of Causality:** Neither SHAP nor LIME establishes physical causal mechanisms; both reflect statistical dependencies learned by the model.
        """
    )
